---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["private_network", {ip: "192.168.33.39"}]


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
 - name: centos-7.2
   driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[django1.8::default]
    attributes:
