---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: production

    data_bags_path: "/home/tux/Documents/repositories/chef-cookbooks/data_bags/vhosts"


    run_list:
      - recipe[learn_chef_httpd::default]
      - recipe[learn_chef_httpd::vhosts]
    attributes:
