name 'django'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures django'
long_description 'Installs/Configures django'
version '0.1.0'

depends 'selinux', '= 0.9.0'
depends 'poise-python', '~> 1.4.0'
depends 'httpd', '~> 0.4.0'
